apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: chainsaw-test
spec:
  namespace: chainsaw-test
  steps:
  - name: Create namespace
    try:
    - apply:
        file: namespace.yaml
    - assert:
        timeout: 5s
        file: namespace-assert.yaml
  - name: Create job
    try:
    - apply:
        file: job.yaml
    - assert:
        timeout: 10s
        file: job-assert.yaml
    - assert:
        file: pod-assert.yaml
