apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
  namespace: chainsaw-demo
spec:
  backoffLimit: 4
  template:
    metadata:
      creationTimestamp: null
      labels:
        batch.kubernetes.io/job-name: testjob
        job-name: testjob
    spec:
      containers:
      - args:
        - Hello, World!
        command:
        - /bin/echo
        image: quay.io/quay/busybox
        imagePullPolicy: Always
        name: busybox
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: testconfigmap
        name: config-volume
status:
  conditions:
    - status: "True"
      type: Complete
  ready: 0
  succeeded: 1
  terminating: 0
